name: Markdown lint

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v15
        continue-on-error: true
        with:
          globs: |
            **/*.md
          config: .markdownlint.json
