name: Unity Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  unity-tests:
    if: ${{ secrets.UNITY_LICENSE != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testMode: [editmode, playmode]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Unity ${{ matrix.testMode }} tests
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: .
          unityVersion: 6000.2.2f1
          testMode: ${{ matrix.testMode }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
